---
name: Publish package to GitHub Packages
on:
  #release:
  #  types: [created]
  push:
    branches:
      - main
    #tags:
    #  - v**
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # https://github.com/actions/checkout/tags
      # https://github.com/actions/setup-java/tags
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and release
        run: mvn --batch-mode release:prepare && mvn --batch-mode release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
